version: '3'
services:
  lw-will-php-cli:
    build:
      context: ./docker/php-cli
      dockerfile: Dockerfile
      args:
        - HOST_USER_UID=${HOST_USER_UID}
        - HOST_USER_GID=${HOST_USER_GID}
    volumes:
      - .:/app
      - composer:/tmp/composer-cache
    environment:
      PHP_IDE_CONFIG: 'serverName=last-wishes.docker'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    profiles:
      - 'cli-tools'        # the profile is needed in order not to start this service with "docker compose up" command
  lw-will-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_DB_USER}
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
    ports:
      - '${MYSQL_DB_HOST_PORT}:3306'
    volumes:
      - mysql:/var/lib/mysql
    restart: always
  lw-will-nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - '${NGINX_HOST_PORT}:80'
    volumes:
      - .:/app
    depends_on:
      - lw-will-php-fpm
    restart: always
  lw-will-php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
      args:
        - HOST_USER_UID=${HOST_USER_UID}
        - HOST_USER_GID=${HOST_USER_GID}
    volumes:
      - .:/app
    depends_on:
      - lw-will-mysql
    restart: always
volumes:
  composer:
  mysql:
